"""CBLens convertible bond pricing package."""

__version__ = "1.0.0"

from .pricer import (
    UniversalCBPricer,
    DEFAULT_COUPON_RATES,
    DEFAULT_FACE_VALUE,
    DEFAULT_REDEMPTION_PRICE,
)
from .pricing_api import (
    price_from_provider,
    price_from_wind,
    price_from_auto,
    batch_price_from_provider,
    batch_price_from_provider_threaded,
)
from .batch_pricing import (
    AdmissionFilterConfig,
    AdmissionFilterResult,
    BATCH_RESULT_COLUMNS,
    build_batch_provider,
    list_upcoming_tradable_from_cache,
    list_batch_codes_from_cache,
    load_batch_results_cache,
    merge_upcoming_pricing_results,
    parse_bond_codes,
    project_batch_cache_path,
    save_batch_results_cache,
    screen_batch_pool_from_cache,
    summarize_batch_results,
    summarize_exclusions,
    write_batch_results_csv,
)
from .backtest import backtest_theoretical_price
from .strategy_backtest import (
    ScoreStrategyConfig,
    backtest_score_strategy,
    build_rebalance_schedule,
    write_strategy_backtest_csv,
)
from .historical_terms import (
    HistoricalBondDataProvider,
    TermsHistoryStore,
    TermsPatch,
    TermsPatchStore,
    default_terms_patch_store,
    project_terms,
    project_terms_history_dir,
    project_terms_patches_path,
    reload_default_terms_patch_store,
    strip_current_status_fields,
)
from .data_providers import (
    DataProvider,
    BondTerms,
    CashflowSchedule,
    WindDataProvider,
    AkshareDataProvider,
    CSVDataProvider,
    auto_data_provider,
    detect_available_providers,
    to_date,
    parse_coupon_string,
)
from .cninfo_provider import (
    CninfoAnnouncementProvider,
    extract_text_from_pdf_bytes,
)
from .paths import (
    APP_NAME,
    app_data_dir,
    asset_path,
    data_dir,
    data_path,
    is_frozen_app,
    project_root,
    seed_data_files,
)
from .cache import (
    TermsCache, TermsBundle, CachedBondDataProvider, CachingDataProvider,
    project_bundle_path,
)
from .cb_data_sync import (
    filter_listed_codes,
    is_terminal_terms,
    refresh_one,
    sync_cb_data,
    sync_cb_terms,
)
from .admission_status import (
    ADMISSION_STATUS_FIELDS,
    changed_admission_fields,
    merge_admission_status,
    refresh_admission_status,
    refresh_admission_status_from_store,
)
from .cb_events import (
    CBEvent,
    CBEventStore,
    apply_events_to_terms,
    classify_announcement_title,
    default_event_store,
    parse_event_from_announcement,
    parse_call_redemption_dates,
    parse_conversion_suspension_terms,
    parse_down_reset_new_price,
    parse_putback_terms,
    project_events_path,
)
from .cb_event_sync import (
    apply_events_to_bundle,
    parse_credit_rating_change,
    parse_credit_rating_terms,
    parse_conversion_price_adjustment,
    parse_outstanding_balance_change,
    parse_terms_patch_from_announcement,
    sync_cb_events,
)

__all__ = [
    "__version__",
    "UniversalCBPricer",
    "DEFAULT_COUPON_RATES",
    "DEFAULT_FACE_VALUE",
    "DEFAULT_REDEMPTION_PRICE",
    "price_from_provider",
    "price_from_wind",
    "price_from_auto",
    "batch_price_from_provider",
    "batch_price_from_provider_threaded",
    "AdmissionFilterConfig",
    "AdmissionFilterResult",
    "BATCH_RESULT_COLUMNS",
    "build_batch_provider",
    "list_upcoming_tradable_from_cache",
    "list_batch_codes_from_cache",
    "load_batch_results_cache",
    "merge_upcoming_pricing_results",
    "parse_bond_codes",
    "project_batch_cache_path",
    "save_batch_results_cache",
    "screen_batch_pool_from_cache",
    "summarize_batch_results",
    "summarize_exclusions",
    "write_batch_results_csv",
    "backtest_theoretical_price",
    "ScoreStrategyConfig",
    "backtest_score_strategy",
    "build_rebalance_schedule",
    "write_strategy_backtest_csv",
    "HistoricalBondDataProvider",
    "TermsHistoryStore",
    "TermsPatch",
    "TermsPatchStore",
    "default_terms_patch_store",
    "project_terms",
    "project_terms_history_dir",
    "project_terms_patches_path",
    "reload_default_terms_patch_store",
    "strip_current_status_fields",
    "DataProvider",
    "BondTerms",
    "CashflowSchedule",
    "WindDataProvider",
    "AkshareDataProvider",
    "CSVDataProvider",
    "CninfoAnnouncementProvider",
    "extract_text_from_pdf_bytes",
    "auto_data_provider",
    "detect_available_providers",
    "TermsCache",
    "TermsBundle",
    "CachedBondDataProvider",
    "CachingDataProvider",
    "filter_listed_codes",
    "is_terminal_terms",
    "refresh_one",
    "sync_cb_data",
    "sync_cb_terms",
    "ADMISSION_STATUS_FIELDS",
    "changed_admission_fields",
    "merge_admission_status",
    "refresh_admission_status",
    "refresh_admission_status_from_store",
    "CBEvent",
    "CBEventStore",
    "apply_events_to_terms",
    "classify_announcement_title",
    "default_event_store",
    "parse_event_from_announcement",
    "parse_call_redemption_dates",
    "parse_conversion_suspension_terms",
    "parse_down_reset_new_price",
    "parse_putback_terms",
    "project_events_path",
    "apply_events_to_bundle",
    "parse_credit_rating_change",
    "parse_credit_rating_terms",
    "parse_conversion_price_adjustment",
    "parse_outstanding_balance_change",
    "parse_terms_patch_from_announcement",
    "sync_cb_events",
    "project_bundle_path",
    "seed_data_files",
    "data_path",
    "data_dir",
    "app_data_dir",
    "asset_path",
    "project_root",
    "is_frozen_app",
    "APP_NAME",
    "to_date",
    "parse_coupon_string",
]
